language: python
sudo: required
install:
    - pip install -r developer_requirements.txt
script:
    - ./run-tests.sh
    - codecov
    - docker run --rm -v "$(pwd):/data" quay.io/pypa/manylinux1_x86_64 bash -c "/data/.travis_build_wheel.sh $TRAVIS_PYTHON_VERSION"
deploy:
    provider: releases
    api_key:
        secure: "DqDkKBKw20riyr1WeRZtMEUlmD9cCJNf/JJD5res8HSx8wUz+rI1aDpk0wCaehdLS2zsvUpf027EHfkseUZaMr3wMfwHQ9FxSEOZ04K8Wmxqk60bzEHwqL6xBe7M3K3RxYUKH6oZDekN2I0imkllHA4v6iG0JGmoacNAos60NdA="
    file_glob: true
    file: 'dist/fastavro-*.whl'
    skip_cleanup: true
    on:
        tags: true
        condition: $TRAVIS_PYTHON_VERSION != *"pypy"*

matrix:
    include:
        - dist: trusty
          python: 2.7
        - dist: trusty
          python: 3.4
        - dist: trusty
          python: 3.5
        - dist: trusty
          python: 3.6
        - dist: xenial
          python: 3.7
        - dist: trusty
          python: pypy
        - dist: trusty
          python: pypy3
