language: python
    - "3.5"
sudo: false
install:
    - pip install tox
script:
    - tox
env:
    - TOXENV=py27
    - TOXENV=py34
    - TOXENV=py35
    - TOXENV=pypy
    - TOXENV=pypy3
    - TOXENV=packaging
