language: python
sudo: required
dist: bionic
arch:
    - amd64
    - arm64-graviton
python:
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8"
    - "pypy3"

before_install:
    - sudo apt-get install -y libsnappy-dev
    - pip install python-snappy
install:
    - pip install -r developer_requirements.txt
script:
    - ./run-tests.sh
    - codecov
    - case $TRAVIS_CPU_ARCH in
      "arm64" | "arm64-graviton2")
        export DOCKER_IMAGE=quay.io/pypa/manylinux2014_aarch64
        ;;
      "amd64" | *)
        export DOCKER_IMAGE=quay.io/pypa/manylinux2014_x86_64
        ;;
      esac

    - if [[ "$TRAVIS_OS_NAME" == "linux" && $TRAVIS_PYTHON_VERSION != *"pypy"* ]]; then
      docker run --rm -v "$(pwd):/data" $DOCKER_IMAGE bash -c "/data/.travis_build_wheel.sh $TRAVIS_PYTHON_VERSION";
      fi;
