language: python
    - "2.7"
    - "3.4"
    - "3.5"
    - "pypy"
sudo: false
install:
    - pip install --user tox
script:
    - tox
env:
    - TOXENV=py27
    - TOXENV=py34
    - TOXENV=py35
    - TOXENV=pypy
    - TOXENV=pypy3
    - TOXENV=packaging
